# Generated by Django 4.1.3 on 2022-11-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(choices=[('UNIT', 'Unit'), ('COMPLETE', 'Complete'), ('COMPONENT', 'Component'), ('DOMAIN', 'Domain')], max_length=10, unique=True)),
            ],
            options={
                'db_table': 'parent_tab',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='requirementFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.TextField(max_length=255)),
                ('filter_name', models.TextField(max_length=100, unique=True)),
                ('parent_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_filter', to='core.parenttab')),
            ],
            options={
                'db_table': 'requirement_filter',
            },
        ),
        migrations.AddField(
            model_name='parenttab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tab', to='core.user'),
        ),
        migrations.CreateModel(
            name='subTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_id', models.TextField(max_length=255)),
                ('req_id', models.TextField(max_length=255)),
                ('testcase_result', models.TextField(max_length=255)),
                ('parent_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tab', to='core.parenttab')),
            ],
            options={
                'db_table': 'sub_tab',
                'unique_together': {('testcase_id', 'req_id')},
            },
        ),
    ]
