# Generated by Django 4.1.3 on 2022-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parenttab_tab_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementfilter',
            name='filter_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='requirementfilter',
            unique_together={('filter_name', 'parent_tab')},
        ),
    ]
