# Generated by Django 4.1.3 on 2022-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requirementfilter_subtab'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementfilter',
            name='filter_name',
            field=models.TextField(default='filter', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
