# Generated by Django 4.1.3 on 2022-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requirementfilter_req_id_alter_subtab_req_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtab',
            name='filter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requirementfilter',
            name='filter_name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
