# Generated by Django 4.1.3 on 2022-11-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subtab_filter_id_alter_requirementfilter_filter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtab',
            old_name='user_id',
            new_name='user',
        ),
    ]
