# Generated by Django 4.1.3 on 2022-11-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subtab_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtab',
            name='filter_id',
        ),
    ]
