# Generated by Django 4.1.3 on 2022-11-25 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_subtab_filter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementfilter',
            name='user_id',
        ),
        migrations.AddField(
            model_name='requirementfilter',
            name='user',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_filter', to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tab', to='core.user'),
        ),
    ]
